// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: permission.proto

package serviceextension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_unknown Action = 0 // don't use this
	Action_CREATE  Action = 1
	Action_READ    Action = 2
	Action_UPDATE  Action = 4
	Action_DELETE  Action = 8
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "unknown",
		1: "CREATE",
		2: "READ",
		4: "UPDATE",
		8: "DELETE",
	}
	Action_value = map[string]int32{
		"unknown": 0,
		"CREATE":  1,
		"READ":    2,
		"UPDATE":  4,
		"DELETE":  8,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_permission_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_permission_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

var file_permission_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "permission.resource",
		Tag:           "bytes,50001,opt,name=resource",
		Filename:      "permission.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Action)(nil),
		Field:         50002,
		Name:          "permission.action",
		Tag:           "varint,50002,opt,name=action,enum=permission.Action",
		Filename:      "permission.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string resource = 50001;
	E_Resource = &file_permission_proto_extTypes[0]
	// optional permission.Action action = 50002;
	E_Action = &file_permission_proto_extTypes[1]
)

var File_permission_proto protoreflect.FileDescriptor

const file_permission_proto_rawDesc = "" +
	"\n" +
	"\x10permission.proto\x12\n" +
	"permission\x1a google/protobuf/descriptor.proto*C\n" +
	"\x06Action\x12\v\n" +
	"\aunknown\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\b\n" +
	"\x04READ\x10\x02\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x04\x12\n" +
	"\n" +
	"\x06DELETE\x10\b:<\n" +
	"\bresource\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\bresource:L\n" +
	"\x06action\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\x0e2\x12.permission.ActionR\x06actionBt\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData []byte
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)))
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permission_proto_goTypes = []any{
	(Action)(0),                        // 0: permission.Action
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_permission_proto_depIdxs = []int32{
	1, // 0: permission.resource:extendee -> google.protobuf.MethodOptions
	1, // 1: permission.action:extendee -> google.protobuf.MethodOptions
	0, // 2: permission.action:type_name -> permission.Action
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		EnumInfos:         file_permission_proto_enumTypes,
		ExtensionInfos:    file_permission_proto_extTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
