// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: service.proto

package serviceextension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_CreateOrUpdateGuildProgress_FullMethodName = "/service.Service/CreateOrUpdateGuildProgress"
	Service_GetGuildProgress_FullMethodName            = "/service.Service/GetGuildProgress"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	CreateOrUpdateGuildProgress(ctx context.Context, in *CreateOrUpdateGuildProgressRequest, opts ...grpc.CallOption) (*CreateOrUpdateGuildProgressResponse, error)
	GetGuildProgress(ctx context.Context, in *GetGuildProgressRequest, opts ...grpc.CallOption) (*GetGuildProgressResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateOrUpdateGuildProgress(ctx context.Context, in *CreateOrUpdateGuildProgressRequest, opts ...grpc.CallOption) (*CreateOrUpdateGuildProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateGuildProgressResponse)
	err := c.cc.Invoke(ctx, Service_CreateOrUpdateGuildProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetGuildProgress(ctx context.Context, in *GetGuildProgressRequest, opts ...grpc.CallOption) (*GetGuildProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuildProgressResponse)
	err := c.cc.Invoke(ctx, Service_GetGuildProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	CreateOrUpdateGuildProgress(context.Context, *CreateOrUpdateGuildProgressRequest) (*CreateOrUpdateGuildProgressResponse, error)
	GetGuildProgress(context.Context, *GetGuildProgressRequest) (*GetGuildProgressResponse, error)
}

// UnimplementedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) CreateOrUpdateGuildProgress(context.Context, *CreateOrUpdateGuildProgressRequest) (*CreateOrUpdateGuildProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateGuildProgress not implemented")
}
func (UnimplementedServiceServer) GetGuildProgress(context.Context, *GetGuildProgressRequest) (*GetGuildProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuildProgress not implemented")
}
func (UnimplementedServiceServer) testEmbeddedByValue() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateOrUpdateGuildProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateGuildProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateOrUpdateGuildProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateOrUpdateGuildProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateOrUpdateGuildProgress(ctx, req.(*CreateOrUpdateGuildProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetGuildProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetGuildProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetGuildProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetGuildProgress(ctx, req.(*GetGuildProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdateGuildProgress",
			Handler:    _Service_CreateOrUpdateGuildProgress_Handler,
		},
		{
			MethodName: "GetGuildProgress",
			Handler:    _Service_GetGuildProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
